apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  destination:
    name: 'in-cluster'
    namespace: devops
  source:
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 'v9.6.1'
    chart: gitea
    helm:
      values: |
        ingress:
          enabled: true
          className: 'nginx'
          annotations:
            external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
            external-dns.alpha.kubernetes.io/hostname: gitea.oakdew.biz
            external-dns.alpha.kubernetes.io/target: 5b48a9ee-7653-461a-bb27-d477fcd388cb.cfargotunnel.com
          hosts:
              - host: gitea.oakdew.biz
                paths:
                  - path: /
                    pathType: Prefix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
