apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  destination:
    name: 'in-cluster'
    namespace: devops
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 'v4.11.3'
    chart: ingress-nginx
    helm:
      values: |
        controller:
          service:
            type: ClusterIP
          ingressClassResource:
            default: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
