apiVersion: v1
kind: ConfigMap
metadata:
  name: taiga-config
  namespace: devops
data:
  TAIGA_ADMIN_USERNAME: admin
  TAIGA_DB_NAME: taiga
  TAIGA_DB_USER: taiga
  TAIGA_ALLOWED_HOSTS: taiga.yourdomain.com
  TAIGA_DB_HOST: taiga-db
  TAIGA_DB_PORT: '5432'
  RABBITMQ_USER: taiga
  RABBITMQ_VHOST: taiga
  TAIGA_SITES_SCHEME: https
  TAIGA_SITES_DOMAIN: taiga.oakdew.biz
  TAIGA_URL: https://taiga.oakdew.biz
  TAIGA_SUBPATH: ''
  TAIGA_WEBSOCKETS_URL: wss://taiga.oakdew.biz
  ATTACHMENTS_MAX_AGE: '360'
