apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-db
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga-db
  template:
    metadata:
      labels:
        app: taiga-db
    spec:
      restartPolicy: Always
      containers:
        - name: taiga-db
          image: postgres:13.16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: taiga-config
                  key: TAIGA_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: taiga-config
                  key: TAIGA_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taiga-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: '512Mi'
              cpu: '250m'
            limits:
              memory: '1Gi'
              cpu: '500m'
          volumeMounts:
            - name: taiga-db-pv
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: taiga-db-pv
          persistentVolumeClaim:
            claimName: taiga-db-pvc
