apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taiga
  namespace: devops
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
    external-dns.alpha.kubernetes.io/hostname: taiga.oakdew.biz
    external-dns.alpha.kubernetes.io/target: 37ed5835-217b-467a-860c-630b6ff8f222.cfargotunnel.com
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - taiga.oakdew.biz
      secretName: oakdew-cert
  rules:
    - host: taiga.oakdew.biz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taiga-gateway
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taiga-gateway
                port:
                  number: 443
