apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  destination:
    name: 'in-cluster'
    namespace: devops
  source:
    repoURL: https://helm.goharbor.io
    targetRevision: 'v1.15.1'
    chart: harbor
    helm:
      values: |
        expose:
          type: ingress
          tls:
            secret:
              secretName: harbor-tls
          ingress:
            hosts:
              core: harbor.oakdew.biz
            className: 'nginx'
            annotations:
              external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
              external-dns.alpha.kubernetes.io/hostname: harbor.oakdew.biz
              external-dns.alpha.kubernetes.io/target: 5b48a9ee-7653-461a-bb27-d477fcd388cb.cfargotunnel.com
        externalURL: harbor.oakdew.biz
        persistence:
          persistentVolumeClaim:
            registry:
              storageClass: nfs-client
            jobservice:
              jobLog:
                storageClass: nfs-client
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
