apiVersion: v1
kind: ConfigMap
metadata:
  name: taiga-config
  namespace: taiga
data:
  TAIGA_ADMIN_USERNAME: admin
  TAIGA_DB_NAME: taiga
  TAIGA_DB_USER: taiga
  TAIGA_ALLOWED_HOSTS: taiga.yourdomain.com
  TAIGA_DB_HOST: taiga-db
  TAIGA_DB_PORT: '5432'
  RABBITMQ_USER: taiga
  RABBITMQ_VHOST: taiga
  TAIGA_SITES_SCHEME: https
  TAIGA_SITES_DOMAIN: taiga.oakdew.biz
  TAIGA_URL: http://taiga.oakdew.biz
  TAIGA_SUBPATH: ''
  TAIGA_WEBSOCKETS_URL: ws://taiga.oakdew.biz
  ATTACHMENTS_MAX_AGE: '360'
  GITLAB_URL: 'http://gitlab:80'
  GITLAB_URL_FRONT: 'http://gitlab.oakdew.biz'
  taiga.conf: |
    server {
      listen 80 default_server;

      client_max_body_size 100M;
      charset utf-8;

      location / {
          proxy_pass http://taiga-front/;
          proxy_pass_header Server;
          proxy_set_header Host $http_host;
          proxy_redirect off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Scheme $scheme;
      }

      location /api/ {
          proxy_pass http://taiga-back/api/;
          proxy_pass_header Server;
          proxy_set_header Host $http_host;
          proxy_redirect off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Scheme $scheme;
      }

      location /admin/ {
          proxy_pass http://taiga-back/admin/;
          proxy_pass_header Server;
          proxy_set_header Host $http_host;
          proxy_redirect off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Scheme $scheme;
      }

      location /static/ {
          alias /taiga/static/;
      }

      location /_protected/ {
          internal;
          alias /taiga/media/;
          add_header Content-disposition "attachment";
      }

      location /media/exports/ {
          alias /taiga/media/exports/;
          add_header Content-disposition "attachment";
      }

      location /media/ {
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Scheme $scheme;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass http://taiga-protected/;
          proxy_redirect off;
      }

      location /events {
          proxy_pass http://taiga-events/events;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_connect_timeout 7d;
          proxy_send_timeout 7d;
          proxy_read_timeout 7d;
      }
    }
