apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taiga
  namespace: taiga
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'
    external-dns.alpha.kubernetes.io/hostname: taiga.oakdew.biz
    external-dns.alpha.kubernetes.io/target: 5860ec34-d45a-45b8-b1e4-9fefd97a59a4.cfargotunnel.com
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - taiga.oakdew.biz
      secretName: taiga-oakdew-cert
  rules:
    - host: taiga.oakdew.biz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taiga-gateway
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taiga-gateway
                port:
                  number: 443

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: taiga-oakdew-cert
  namespace: taiga
spec:
  secretName: taiga-oakdew-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - taiga.oakdew.biz
