apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sealed-secrets-controller
  namespace: sealed-secrets
rules:
  - apiGroups: ['bitnami.com']
    resources: ['sealedsecrets']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'delete']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sealed-secrets-secrets-access
  namespace: sealed-secrets
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'delete']
  - apiGroups: ['']
    resources: ['events']
    verbs: ['create', 'patch', 'update']
