apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
  namespace: sealed-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sealed-secrets
  template:
    metadata:
      labels:
        app: sealed-secrets
    spec:
      serviceAccountName: sealed-secrets-controller
      containers:
        - name: sealed-secrets
          image: bitnami/sealed-secrets-controller:latest
          ports:
            - containerPort: 8080
          args:
            - '--key-renew-period=0'
          resources:
            requests:
              memory: '256Mi'
              cpu: '200m'
            limits:
              memory: '512Mi'
              cpu: '300m'
