apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sealed-secrets-pvc
  namespace: sealed-secrets
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
