apiVersion: v1
kind: ServiceAccount
metadata:
  name: sealed-secrets-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sealed-secrets-role
  namespace: sealed-secrets
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'create', 'update', 'list', 'watch']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealed-secrets-rolebinding
  namespace: sealed-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secrets-role
subjects:
  - kind: ServiceAccount
    name: sealed-secrets-controller
    namespace: sealed-secrets
