apiVersion: v1
kind: Service
metadata:
  name: sealed-secrets
spec:
  selector:
    app: sealed-secrets
  namespace: sealed-secrets
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
