apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
  namespace: devops
type: Opaque
data:
  TUNNEL_TOKEN: ZXlKaElqb2lNVE14TVdSbU5qWTBaVEZtTVdRd05tSTNZamM1WmpFek9EQmhNVGt3WlRRaUxDSjBJam9pTXpkbFpEVTRNelV0TWpFM1lpMDBOamRoTFRnMk1HTXROak13WWpabVpqaG1Nakl5SWl3aWN5STZJazFIVlRSTmVrbDNUakpaZEU1RVRYbFphVEF3VFcxVk1FeFVhM3BOUkZsMFRWZEthMXB0UlRGT01rMTNUakpLYXlKOQ==
